services:
  app:
    init: true
    build:
      dockerfile: Dockerfile
      context: .
      target: dev
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - PDF_DEBUG=${PDF_DEBUG}
